### ISSUE TITLE
Less Frequent Releases

### ISSUE THREAD

**Issue by alsutton** [awslabs/aws-sdk-kotlin#1156]
### Describe the feature

The Kotlin SDK is now stable, but there seem to be daily releases, which creates a lot of churn for folk using automatic dependency upgrade systems (e.g. GitHub dependabot), and, as each upgrade comes with some risk, means that there is a need for a daily check to ensure that downstream repos don't end up blocked due to a bug.

### Is your Feature Request related to a problem?

A high release frequency creates additional work for downstream repositories

### Proposed Solution

Weekly, or less frequent releases.

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Kotlin SDK version used

1.0.x

### Platform (JVM/JS/Native)

JVM

### Operating System and version

Linux

**Comment by lauzadis** [comment]
Hi Al, thanks for opening the issue. We release a new version of the AWS SDK for Kotlin when there are updates made to the AWS models, which happens essentially every day. The same release cadence is followed by most other AWS SDKs, including [Java](https://github.com/aws/aws-sdk-java-v2/tags), [Go](https://github.com/aws/aws-sdk-go-v2/tags), and [PHP](https://github.com/aws/aws-sdk-php/tags) to ensure a consistent experience for customers, and we won't be deviating from that.

Dependabot should only be sending you notifications when one of your dependencies has been marked as vulnerable in the [GitHub Advisory Database](https://github.com/advisories). The AWS SDK for Kotlin has not been listed there. Am I misunderstanding your usage of Dependabot, do you get notified every time a new version of the SDK is released?

**Comment by alsutton** [comment]
Dependabpt is creating a PR most days, but only for S3;

![image](https://github.com/awslabs/aws-sdk-kotlin/assets/430714/ccf9a527-fc93-4107-81a9-561a3c94726c)

**Comment by lauzadis** [comment]
Ok I see, thanks for the info! A few options I can recommend are: 
- [adjust how frequently Dependabot checks for outdated dependencies](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates#frequency-of-dependabot-pull-requests) (weekly, monthly)
    -  Unfortunately, I don't think it's possible to change the scan frequency for a single package
- [disable automatic dependency upgrades for `aws-sdk-kotlin`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/customizing-dependency-updates#ignoring-specific-dependencies-for-dependabot-version-updates)


I'll be closing this issue because we don't plan to change our release cadence. It's synchronized with other SDKs and we want to ensure customers always have access to the latest AWS models.
