### ISSUE TITLE
Kotlin SDK is explicitly nullable at too many points

### ISSUE THREAD

**Issue by LDVSOFT** [awslabs/aws-sdk-kotlin#1242]
### Describe the bug

It looks like while codegen is perfomred from the API definitions to the Kotlin source, a lot of fields are stored as nullable even though those are always provided by the API, ending up with the need to perform I-swear-by-the-name-of-my-mother operator much too often.

Consider the example of my write-up for a script:
```kt
val clusters = EmrClient {
    // ...
}.use { emr ->
    emr
        .listClustersPaginated()
        .transform { response ->
            response.clusters
                .orEmpty()                             // Can it be null?!
                .asSequence()
                .map { ClusterId(it.id!!, it.name!!) } // Can those be null?!
                .forEach { emit(it) }
        }
        .filter { it.name == "..." }
        .take(100)
        .map {
            val cluster = emr.describeCluster {
                clusterId = it.id
            }.cluster!!                               // Really?!

            ClusterInfo(
                id = cluster.id!!,                    // Again, why nullable?
                createdAt =                           // ...
                    cluster.status!!.timeline!!.creationDateTime!!,
                    ...
                )
        }
        .toList()
}
```

### Expected behavior

Being written in Kotlin, I'd expect the SDK to properly use the built-in nullability of the language to express the always present fields.

### Current behavior

Currently not only this information isn't available but also it creates a lot of noise for Kotlin users, since compared to Java APIs Kotlin won't be lenient towards the library in Kotlin.

### Steps to Reproduce

Snippet from above should be enough, but it's not the runtime flaw.

### Context

I'm sorry if that was already discussed somewhere, I tried to look through the issue history but haven't found anything.

I see that Java SDK [has the same issue](https://github.com/aws/aws-sdk-java-v2/issues/505), but at least there it doesn't require a `!!` at every step.

### AWS Kotlin SDK version used

1.0.62

### Platform (JVM/JS/Native)

JVM OpenJDK 17

### Operating System and version

Ubuntu 22.04 amd64

**Comment by ianbotsf** [comment]
Hi @LDVSOFT, thanks for the issue. Unfortunately, the underlying service API responses are not guaranteed to contain those values (even if they are present _most_ of the time). For instance, the EMR [`listClusters`](https://docs.aws.amazon.com/emr/latest/APIReference/API_ListClusters.html#API_ListClusters_ResponseSyntax) operation in your script returns an array of [`ClusterSummary`](https://docs.aws.amazon.com/emr/latest/APIReference/API_ClusterSummary.html) objects but the EMR documentation shows that none of the fields for that type are "required", meaning they _could_ be null in the response object. It's the same with many other types in the Smithy models for AWS services.

Moreover, we've found that services may occasionally change a member from non-nullable to nullable when a new mode or feature is introduced. If that happened and a user code was still running with an old version of the client not expecting nulls, the response would be unparseable and throw an exception at runtime.

For these two reasons we codegen most request and response types as nullable. That's regrettable given Kotlin's incorporation of nullability into the type system but we cannot safely treat most members as non-nullable without violating the spirit of Kotlin's null guarantees.

That said, Kotlin does have fantastic support for null-coalescing which can increase the runtime safety of your code and improve debuggability if/when unexpected nulls are encountered in responses. Instead of `!!`, I suggest `?.` and `?;` like so:

```kotlin
val clusters = EmrClient {
    // ...
}.use { emr ->
    emr
        .listClustersPaginated()
        .transform { response ->
            response.clusters
                .orEmpty()
                .asSequence()
                .map { ClusterId(it.id ?: "(no ID)", it.name ?: "(unnamed)") }
                .forEach { emit(it) }
        }
        .filter { it.name == "..." && it.id != "(no ID)" }
        .take(100)
        .map {
            val cluster = checkNotNull(
                emr.describeCluster { clusterId = it.id }.cluster,
                "Cannot find cluster $it"
            )

            ClusterInfo(
                id = cluster.id ?: "(no ID)",
                createdAt = cluster.status?.timeline?.creationDateTime ?: Instant.fromEpochSeconds(0),
                ...
            )
        }
        .toList()
}
```
