### ISSUE TITLE
GroupGrantee

### ISSUE THREAD

**Issue by mgroth0** [awslabs/aws-sdk-kotlin#1251]
### Describe the feature

In the java V1 S3 SDK, we have [com.amazonaws.services.s3.model.GroupGrantee](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/GroupGrantee.java), an enum of URIs making grantees such as AllUsers typesafe for the user. I have searched this repo, and I could not find any trace of it here.

### Is your Feature Request related to a problem?

This is just about type safety. We can easily copy and paste the string into our own variable, but this is a downgrade from the type safety offered from the java library.

### Proposed Solution

The GroupGrantee enum can be copied into the kotlin sdk.

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Kotlin SDK version used

1.0.73

### Platform (JVM/JS/Native)

JVM

### Operating System and version

Mac

**Comment by lauzadis** [comment]
Hi, thanks for the feature request. Java V1 was the first AWS SDK ever published (March 25, 2010), and most of these "convenience" features were implemented and maintained manually at the time. 

Now, almost all of the SDKs are auto-generated by models that the service team (in this case, S3) owns. That helps us maintain the 300+ AWS services with little manual, per-service effort.

S3 models the fields as a string and the Kotlin SDK must respect that. S3 can't easily change the field to an enum because it would be considered a breaking change. 
```
// s3.json
        "com.amazonaws.s3#Grantee": {
            ...
            "URI": {
                "target": "com.amazonaws.s3#URI",
                "traits": {
                    "smithy.api#documentation": "<p>URI of the grantee group.</p>"
                }
            },
        }
...
        "com.amazonaws.s3#URI": {
            "type": "string"
        },
```

**Comment by lauzadis** [comment]
It wouldn't be a breaking change for S3 to simply add a new `GroupGrantee` enum. If they did that, Kotlin SDK would begin generating it and you could use it. But it wouldn't be explicitly linked to the `com.amazonaws.s3#URI` shape, users would need to know that `GroupGrantee` exists and where to use it.

It **would** be a breaking change for S3 to modify the URI shape like this:
```
"com.amazonaws.s3#URI": {
    "type": "com.amazonaws.s3#GroupGrantee" // new enum
},
```

To avoid a breaking change, S3 would need to keep the type as `string`. So, no new type safety would be introduced. I agree it could be convenient to make a `GroupGrantee` enum with the common values used by S3, but the type of `com.amazonaws.s3#URI` will still need to be a string.

**Comment by lauzadis** [comment]
This is something I would recommend to implement yourself. S3 models the URIs as a string and does not provide a `GroupGrantee` enum. Even if they were to add a `GroupGrantee` enum, it could not be linked to `com.amazonaws.s3#URI` (because of the breaking change implications discussed above). Users would need to know when and where to use the `GroupGrantee` enum since it would not be tied to any shapes, and the experience would still be flawed.
