### ISSUE TITLE
ec2 error modeling

### ISSUE THREAD

**Issue by kggilmer** [awslabs/aws-sdk-kotlin#278]
The Ec2 smithy model does not specify errors for operations, however the service does return error codes.  These error codes do not map to defined shapes.  As it stands, errors returned from Ec2 throw `UnknownServiceErrorException`.  There is a page https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html#CommonErrors which defines errors that may apply to an given operation.  We may want to do a model mutation to model these errors or perhaps model one specific error to prevent customers having to deal with `UnknownServiceErrorException`.

**Comment by aajtodd** [comment]
We have no plans to implement this. If the model doesn't contain the errors then a generic `Ec2Exception` with the corresponding error code will be what is thrown. We don't want to be on the hook for defining all of these custom exceptions and implementing a customization for all of EC2 that try's to map error codes to a more concrete exception. It gives no additional details than the error code already does it just does so through a type rather than a string.
