### ISSUE TITLE
CreateMultipartUpload doesn't get signed correctly

### ISSUE THREAD

**Issue by wingsofovnia** [awslabs/aws-sdk-kotlin#588]
### Describe the bug

Initializing a multi-upload fails if content-type is passed: `The request signature we calculated does not match the signature you provided. Check your key and signing method.` According tho AWS [doc](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CreateMultipartUpload.html), content type header ~ `A standard MIME type describing the format of the object data` so it is expected.

### Expected behavior

A multi-upload is initialized for and object with the given MIME type.

### Current behavior

The request fails with:
```
aws.sdk.kotlin.services.s3.model.S3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

### Steps to Reproduce

```
val pendingFile = s3Client.createMultipartUpload {
      bucket = "bucket"
      key = "key"
      contentType = "video/mp4"
}
```

### Possible Solution

Dropping `contentType` "fixes" the issue.

It might be related to https://github.com/awslabs/aws-sdk-kotlin/issues/567.

There is not a single test that covers this SDK API. Would be great to have some coverage.

### AWS Kotlin SDK version used

0.14.3-beta

### Platform (JVM/JS/Native)

JVM

### Operating System and version

Ubuntu

**Comment by ianbotsf** [comment]
Thanks for the bug report @wingsofovnia, I've reproduced the issue with the sample you provided. We'll get started root causing this and working on a fix!

**Comment by ianbotsf** [comment]
It looks like our request adapter [strips out the `Content-Type` header](https://github.com/awslabs/smithy-kotlin/blob/main/runtime/protocol/http-client-engines/http-client-engine-ktor/common/src/aws/smithy/kotlin/runtime/http/engine/ktor/KtorRequestAdapter.kt#L45-L48) because of how Ktor requires that header to be set on the body (and _not_ as a typical header). We correctly reconfigure content type for non-empty bodies but neglected to do so for empty bodies. Thus, the signature calculation includes the `Content-Type` header but the actual wire request does not, leading to the signature mismatch.

**Comment by ianbotsf** [comment]
The PR for this fix has been merged to **main** and will be included in the next release (likely later this week).
