### ISSUE TITLE
Support for DynamoDB with DAX

### ISSUE THREAD

**Issue by vgiguere** [awslabs/aws-sdk-kotlin#658]
### Describe the issue

I have been digging and could not find a way to build a DynamoDB Client that can route operations through a DAX Cluster.
I see a DaxClient in aws.sdk.kotlin:dax-jvm, but no implementation of the DynamoDbClient interface for DAX.

Is it something that is being worked on right now?
Is there an alternative?

Thanks

### Steps to Reproduce

Build a DynamoDBClient that can use a dax endpoint

### Current behavior

There seems to be a DaxClient in aws.sdk.kotlin:dax-jvm but it only exposes functionalities to manage the dax cluster, not access DynamoDB through it.

There is no implementation of the DynamoDBClient interface for DAX

### AWS Kotlin SDK version used

0.15.0, 0.16.0, 0.17.0-beta

### Platform (JVM/JS/Native)

JVM

### Operating System and version

Mac OSX 12.3.1

**Comment by ianbotsf** [comment]
Hi @vgiguere, you're right there is currently no support for routing DynamoDB access through a DAX cluster in the AWS SDK for Kotlin. [Language-specific DAX clients](http://dax-sdk.s3-website-us-west-2.amazonaws.com/) are separate from the SDKs themselves and thus managed by a different team. I'm searching for the right contact internally to route the request to so that we can get this on a roadmap.

This work may not happen right away since the Kotlin SDK is not yet GA/1.0.

**Comment by vgiguere** [comment]
Thank you @ianbotsf 

In the meantime, are you aware of a workaround that would allow us to proceed with using DAX?

**Comment by ianbotsf** [comment]
No, I'm not aware of a way to do that. You could use the DAX client for Java (with the Java AWS SDK) but that would not directly provide an interface with coroutine support. You could wrap the Java calls in `async`/`launch` but that wouldn't take full advantage of suspend points so it'd be less efficient. A full-fledged Kotlin client would be the best way and that doesn't exist yet.

**Comment by ianbotsf** [comment]
Since the AWS SDK for Kotlin cannot host DAX support directly, please file a support case with AWS via the console. They'll work with the service team to get your request prioritized.

Are there any other questions I can answer on this topic?
