### ISSUE TITLE
DynamoDB: Model duplication

### ISSUE THREAD

**Issue by eiennohito** [awslabs/aws-sdk-kotlin#826]
### Describe the feature

There are some places where request objects define different API entries with almost identical parameters.

For example, `TableCreationParameters` of `ImportTableRequest` is almost a copy of `CreateTableRequest`. 

### Is your Feature Request related to a problem?

It would be nice if it were possible to generalize over such API entries, e.g. define table definitions in a single place

### Proposed Solution

Provide a way to generalize code over almost completely same request objects

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Kotlin SDK version used

0.19.5-beta

### Platform (JVM/JS/Native)

JVM

### Operating System and version

Linux

**Comment by ianbotsf** [comment]
Hi @eiennohito, thanks for reaching out.

The AWS SDK for Kotlin's service types (e.g., `CreateTableRequest` and `TableCreationParameters`) are code-generated from models maintained by service teams themselves. Service model authors often reuse types between different APIs but may choose not to because the APIs offer divergent capabilities (or may in the future). In the case of the APIs you mentioned, **CreateTable** supports additional features like creating LSIs, configuring DynamoDB Streams, and tagging, whereas **ImportTable** does not.

Our code generator cannot infer any relationship between the two types based solely on their structure because they may diverge over time or may assign different meaning to identically-named parameters. Given that the Kotlin language itself provides no generalized solution for this (e.g., duck typing, type classes, etc.), I do not believe we can implement this feature at this time.
