### ISSUE TITLE
Kotlin Service Clients do not work with the use syntax in Android Studio Eel

### ISSUE THREAD

**Issue by scmacdon** [awslabs/aws-sdk-kotlin#830]
### Describe the bug

The Kotlin SDK works in Android Studio provided you declare a Service Client like this:

 val snsClient = SnsClient{
            region = "us-west-2"
            credentialsProvider = getStatic()
        }

However, when you attempt to use this syntax, the app does not work: 

 S3Client { region = "us-west-2" }.use { s3Client ->
...
}

 

### Expected behavior

The use syntax to work in Android Studio.

### Current behavior

App crashes. 

### Steps to Reproduce

Create a small project in Android Studio. 

### AWS Kotlin SDK version used

0.19.0-beta

### Platform (JVM/JS/Native)

JVM

### Operating System and version

Windows 10

**Comment by lauzadis** [comment]
I'm able to replicate this and see a `NetworkOnMainThreadException`. Is that the same exception you're seeing? If not, can you post some logs?

If you are seeing this exception, it means you are making a network call on the main thread which is against Android conventions and results in a crash. There are a handful of ways to address this.

1) Launch the work in a `new Thread(...)`
2) Disable Strict Mode which is throwing the exception
```kotlin
if (android.os.Build.VERSION.SDK_INT > 9) {
    StrictMode.ThreadPolicy gfgPolicy =
        new StrictMode.ThreadPolicy.Builder().permitAll().build();
    StrictMode.setThreadPolicy(gfgPolicy);
}
```
3) Annotate the function doing the S3 call with the `@Background` annotation

**Comment by lauzadis** [comment]
I narrowed it down a bit further, the `NetworkOnMainThreadException` gets called specifically after calling the client's `.close()` method. This is due to how HTTP engine cleanup works in the SDK. 

I was able to resolve the issue by wrapping my network requests in a `thread { ... }` block, which is provided by the Kotlin standard library. To avoid this issue in the future, users should not make network requests on the main thread in Android, as this will result in the exception you're seeing.
