### ISSUE TITLE
bucketExists

### ISSUE THREAD

**Issue by mgroth0** [awslabs/aws-sdk-kotlin#873]
### Describe the feature

I see ` S3Client.bucketExists` in some example code. Is it not robust enough to include in the library?

### Is your Feature Request related to a problem?

No

### Acknowledge

- [X] I may be able to implement this feature request

### AWS Kotlin SDK version used

0.21.1-beta

### Platform (JVM/JS/Native)

JVM

### Operating System and version

Mac OSX

**Comment by lauzadis** [comment]
The AWS SDK for Kotlin is model-driven and almost completely code-generated, which means we generate the SDK from a model file instead of writing it by hand. The advantage of this is it minimizes developer time spent writing custom code for each AWS service. Because of this, we don't add custom extension functions at a per-service level. The example you've seen with `S3Client.bucketExists` is likely from AWS SDK for Java v1, or a different SDK which was created before code-generation started, and therefore had a bunch of those custom utility functions. 

The example code snippet you've provided seems like it would work. [`headBucket`](https://sdk.amazonaws.com/kotlin/api/latest/s3/aws.sdk.kotlin.services.s3/head-bucket.html) is the method to use for checking if a bucket exists, there is also [`headObject`](https://sdk.amazonaws.com/kotlin/api/latest/s3/aws.sdk.kotlin.services.s3/head-object.html) which does the same thing for objects.

**Comment by aajtodd** [comment]
The generated S3 client includes waiters for both bucket and object exists/not-exists.

See https://sdk.amazonaws.com/kotlin/api/latest/s3/aws.sdk.kotlin.services.s3.waiters/index.html (specifically `waitUntilObjectExists`).

All services are generated this way if they have waiters look at the `waiters` subpackage to see what is available
